In [1]:
import numpy as np 

In [2]:
l=[1,2,3,4]
ar=np.array(l)

In [9]:
l2=[[1,2,3],[4,5,6],[7,8,9]]
ar=np.array(l2)
ar.ndim

2

In [10]:
l2=[[[1,2,3],[4,5,6],[7,8,9]]]
arr=np.array(l2)
arr.ndim

3

In [11]:
b=np.matrix(l)

In [15]:
b
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [16]:
c=a

In [17]:
c

array([1, 2, 3, 4])

In [18]:
c[0]=200

In [20]:
c[2]=6

In [21]:
c

array([200,   2,   6,   4])

In [22]:
a

array([200,   2,   6,   4])

In [23]:
d=np.copy(a)

In [24]:
d

array([200,   2,   6,   4])

In [25]:
a[1]=400

In [26]:
a

array([200, 400,   6,   4])

In [27]:
d

array([200,   2,   6,   4])

In [30]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [31]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [33]:
l=[2,3,4,5,6]
ar=np.array(l)

In [34]:
ar

array([2, 3, 4, 5, 6])

In [35]:
ar2=np.array([[1,2,3],[4,5,6]])

In [36]:
ar2.ndim

2

In [38]:
ar2.shape

(2, 3)

In [41]:
ar2.dtype

dtype('int32')

In [42]:
arr22=np.array([(1.4,45,6),(2,3,4)])
arr22.dtype

dtype('float64')

In [46]:
np.linspace(1,5,num=10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [50]:
np.zeros(5)
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [48]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [55]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [63]:
arr=np.random.randn(3,4)

In [64]:
import pandas as pd

In [65]:
pd.DataFrame(arr)

0         1         2         3
0 -0.934851  0.175335  1.543429 -0.234776
1  1.216783  0.416147 -0.015951 -0.526123
2 -1.021088  0.967357 -0.135371  2.534437

In [68]:
np.random.rand(3,3)

array([[0.58961383, 0.7945589 , 0.50684104],
       [0.0779649 , 0.45808104, 0.90410523],
       [0.77288192, 0.97293682, 0.67250838]])

In [74]:
np.random.randint(1,100,(3,3))

array([[25, 41, 70],
       [82, 70, 22],
       [41, 78, 29]])

In [76]:
pd.DataFrame(np.random.randint(1,110,(300,400))).to_csv("data.csv")

In [78]:
arr=np.random.rand(3,4)

In [79]:
arr

array([[0.23769125, 0.39658552, 0.93419239, 0.98134148],
       [0.68727084, 0.24227493, 0.55209627, 0.87067355],
       [0.03773709, 0.64393268, 0.92681683, 0.44761031]])

In [91]:
arr.reshape(6,-1)

array([[0.23769125, 0.39658552],
       [0.93419239, 0.98134148],
       [0.68727084, 0.24227493],
       [0.55209627, 0.87067355],
       [0.03773709, 0.64393268],
       [0.92681683, 0.44761031]])

In [92]:
arr[1][1]

0.24227493495324326

In [101]:
arr[2:51,1]

array([0.64393268])

In [103]:
arr=np.random.randint(1,100,(5,5))

In [104]:
arr

array([[31, 60, 92, 51, 50],
       [19,  2, 52, 95, 85],
       [58, 21, 59, 21, 28],
       [80, 29,  8, 92, 67],
       [ 6, 19, 85, 54, 54]])

In [106]:
arr[arr>30]

array([31, 60, 92, 51, 50, 52, 95, 85, 58, 59, 80, 92, 67, 85, 54, 54])

In [108]:
arr[2:4,[1,2]]

array([[21, 59],
       [29,  8]])