In [1]:
import numpy as np

In [4]:
arr=np.random.randint(1,10,(3,4))

In [5]:
arr.reshape(4,3)

array([[8, 8, 9],
       [9, 9, 5],
       [3, 1, 1],
       [3, 6, 5]])

In [6]:
arr1=np.array([1,2,3,4,5])

In [7]:
arr1

array([1, 2, 3, 4, 5])

In [9]:
np.expand_dims(arr1,axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [11]:
np.expand_dims(arr1,axis=0)

array([[1, 2, 3, 4, 5]])